import '@/assets/styles/reset.css'
import '@/assets/styles/globals.scss'
import { ReactNode } from 'react'
import { Metadata } from 'next'
import { baronNeue, montserrat, orelo, passionOne } from '@/constants/fonts'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body className={`${montserrat.variable} ${baronNeue.variable} ${passionOne.variable} ${orelo.variable}`}>
        <main>{children}</main>
      </body>
    </html>
  )
}
